### ISSUE TITLE
How to generate plot?

### ISSUE THREAD

**Issue by vgoklani** [jquesnelle/scaled-rope#3]
Thank you for sharing this!

I'd like to review your steps for generating the plots I've seen on twitter.

Could you please include your plot generation script.. I know it's calling perplexity.py, but I'd like to re-trace your steps exactly. Then I can tweak it :)

**Comment by jquesnelle** [comment]
Add `--output-file` as an argument and it will output a CSV file with the proper X/Y data. To be honest after that I just pasted it into Google Sheets 😂
