### ISSUE TITLE
Finetune Example

### ISSUE THREAD

**Issue by M-Chris** [jquesnelle/scaled-rope#4]
Awesome job on this

Do you have any examples of a fine-tune cli / setup to show llama3b 4096 | 6144?

**Comment by StrangeTcy** [comment]
My questions are of the same sort, but rather about the training/finetuning args and the dataset to use

**Comment by DumoeDss** [comment]
So do you have any examples of a fine-tune cli / setup to show llama3b?

**Comment by M-Chris** [comment]
Realized this was still open. 
Even though the script is pretty standard would have been great to see _at the time of the post_, a few use-case/examples with ntk parts and other variations found viable for fine-tuning.. closing it, best of luck 👍 

[This may be of interest to other readers](https://github.com/kyleliang919/Long-context-transformers)
